@host=http://127.0.0.1:8000/
@username=new_user
@email=new@user.com
@password=new_user_password
@token=161d5792cf0179a3d9694d8206021d78030461f2


### Create new account
POST {{host}}/auth/users/
Content-Type: application/json

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "re_password": "{{password}}"
}


### Login
POST {{host}}/auth/token/login/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

### Logout
POST {{host}}/auth/token/logout/
Authorization: token {{token}}

### Create new question
POST {{host}}/api/v1/questions/
Content-Type: application/json
Authorization: Token {{token}}

{
    "content": "Is this question the best test one ever asked!?"
}


### Get question list
GET {{host}}/api/v1/questions/
Authorization: Token {{token}}
